parameters:
    ton.email_bundle.dir: '%kernel.project_dir%/var/emails'
    ton.email_bundle.swift.file_transport.class: Ton\EmailBundle\Swift\FileTransport
    ton.email_bundle.email_reader.class: Ton\EmailBundle\EmailReader

services:
    ton.email_bundle.swift.file_transport:
        class: "%ton.email_bundle.swift.file_transport.class%"
        calls:
            - [setDir, ["%ton.email_bundle.dir%"]]
    swiftmailer.mailer.transport.file:
        alias: ton.email_bundle.swift.file_transport
    ton.email_bundle.email_reader:
        class: "%ton.email_bundle.email_reader.class%"
        arguments:
            - "%ton.email_bundle.dir%"
